<a href="https://colab.research.google.com/github/GinaFrd/ginafrd/blob/main/Amazon1_productos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exploratory Data Analysis
-Dataset Original: [Kaggle](https://www.kaggle.com/datasets/nguyenngocphung/10000-amazon-products-dataset)

## Objetivo:
1. *) Número de reviews medio y cual es el maximo

3. *) Número de respuestas medio y cual es el maximo

5. *) Trabajar con libras (ver la media cuanto es)

# Business Understanding
-El dataset original es un conjunto de datos que contiene más de 10,000 productos diferentes de Amazon.
- Filas: 10,005
- Columnas: 14
> Modelo de datos
- -product_name : cualitativa, nominal, string
- -manufacturer: cualitativa, nominal, string
- -price: cualitativa numerica, in, de razon
- -number_available_in_stock: cualitativa numerica, in, de razon
- -number_of_reviews: cualitativa numerica, in, de razon
- -number_of_answered_questions: cualitativa numerica, in, de razon
- -average_review_rating: cualitativa numerica, in, de intervalo
- -amazon_category_and_sub_category: cualitativa, nominal, string
- -description: cualitativa, nominal, string
- -product_information: cualitativa, nominal, string
- -product_description :cualitativa, nominal, string
- -items_customers_buy_after_viewing_this_item :cualitativa, nominal, string
- -customer_questions_and_answers: cualitativa, nominal, string

###Paso 1
Importo las librerías que voy a usar

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import plotly.express as px
import string

### Paso 2
Subo el archivo y hago un head para ver cómo están los datos, sobre todo me doy cuenta del gran número de columnas, el siguiente paso es eliminar las columnas porque no van a ser necesarias para mi objetivo.

In [ ]:
amazon = pd.read_csv('Amazon_Products.csv')
amazon.head(2)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (5,6,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,uniq_id,product_name,manufacturer,price,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,description,...,Unnamed: 885,Unnamed: 886,Unnamed: 887,Unnamed: 888,Unnamed: 889,Unnamed: 890,Unnamed: 891,Unnamed: 892,Unnamed: 893,Unnamed: 894
0,eac7efa5dbd3d667f26eb3d3ab504464,Hornby 2014 Catalogue,Hornby,£3.42,5 new,15.0,1.0,4.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Product Description Hornby 2014 Catalogue Box ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,b17540ef7e86e461d37f3ae58b7b72ac,FunkyBuys® Large Christmas Holiday Express Fes...,FunkyBuys,£16.99,NaN,2.0,1.0,4.5 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Size Name:Large FunkyBuys® Large Christmas Hol...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Paso 3
Borrado de columnas incesarias a partir de la 15
  Dos fuentes:

*   > invoices.drop(['client'], axis=1) [drop](https://www.analyticslane.com/2019/03/25/como-eliminar-columnas-y-filas-en-un-dataframe-pandas/\)
*   >data.iloc[:,1:3] = [iloc](https://www.askpython.com/python/built-in-methods/python-iloc-function)

In [ ]:
## amazon.drop(["Unnamed: 885"], axis =1) "funciona pero no es viable tendria que escribir todas las columnas"

(amazon.iloc[:,1:14]) #he borrado todas las columnas innecesarias con iloc

,product_name,manufacturer,price,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers
0,Hornby 2014 Catalogue,Hornby,£3.42,5 new,15.0,1.0,4.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Product Description Hornby 2014 Catalogue Box ...,Technical Details Item Weight640 g Product Dim...,Product Description Hornby 2014 Catalogue Box ...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Does this catalogue detail all the previous Ho...
1,FunkyBuys® Large Christmas Holiday Express Fes...,FunkyBuys,£16.99,NaN,2.0,1.0,4.5 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Size Name:Large FunkyBuys® Large Christmas Hol...,Technical Details Manufacturer recommended age...,Size Name:Large FunkyBuys® Large Christmas Hol...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,can you turn off sounds // hi no you cant turn...
2,CLASSIC TOY TRAIN SET TRACK CARRIAGES LIGHT EN...,ccf,£9.99,2 new,17.0,2.0,3.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,Technical Details Manufacturer recommended age...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,http://www.amazon.co.uk/Train-With-Tracks-Batt...,What is the gauge of the track // Hi Paul.Trut...
3,HORNBY Coach R4410A BR Hawksworth Corridor 3rd,Hornby,£39.99,NaN,1.0,2.0,5.0 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,Technical Details Item Weight259 g Product Dim...,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,NaN,NaN
4,Hornby 00 Gauge 0-4-0 Gildenlow Salt Co. Steam...,Hornby,£32.19,NaN,3.0,2.0,4.7 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Product Description Hornby RailRoad 0-4-0 Gild...,Technical Details Item Weight159 g Product Dim...,Product Description Hornby RailRoad 0-4-0 Gild...,http://www.amazon.co.uk/Hornby-R2672-RailRoad-...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999,Batman 1966 TV Series Action Figures - The Rid...,Mattel,£22.95,5 new,3,3.0,5.0 out of 5 stars,Hobbies > Collectible Figures & Memorabilia > ...,DC 66 Batman Classic TV Series 6 Inch Riddler ...,Technical Details Item Weight136 g Product Dim...,DC 66 Batman Classic TV Series 6 Inch Riddler ...,NaN,NaN
10000,"Star Wars Costume, Kids Stormtrooper Costume S...",Star Wars,£39.99,NaN,1,3.0,4.0 out of 5 stars,Characters & Brands > Star Wars > Toys,NaN,Technical Details Additional Information AS...,NaN,http://www.amazon.co.uk/Storm-Trooper-Costume-...,NaN
10001,Defiance Lawkeeper Metal Badge Prop Replica,Olde Scotland Yard Ltd.,£43.99,3 new,1,3.0,5.0 out of 5 stars,Novelty & Special Use > Novelty > Accessories ...,*Includes 1x Badge with holder and chain *High...,Technical Details Item Weight159 g Product Dim...,*Includes 1x Badge with holder and chain *High...,http://www.amazon.co.uk/Olde-Scotland-Yard-Ltd...,NaN
10002,Justice League of America Series 3 Green Lante...,DC Comics,£49.81,3 new,1,3.0,5.0 out of 5 stars,Hobbies > Collectible Figures & Memorabilia > ...,Designed by Ed BenesIt's here - the third seri...,Technical Details Item Weight181 g Product Dim...,Designed by Ed BenesIt's here - the third seri...,NaN,NaN
10003,Star Wars 1/72 Y-Wing Starfighter,Bandai,£21.20,31 new,11,3.0,4.5 out of 5 stars,Characters & Brands > Star Wars > Toys,NaN,Technical Details Item Weight299 g Product Dim...,NaN,NaN,NaN

### Paso 4
Establezco qué datos son necesarios para mis objetivos
1. *) Número de reviews medio y cual es el maximo
		Para la media: Necesitaré sumar todas las reviews de todos los productos y dividir la suma por el numero de productos pero se puede usar el siguiente código.
		codigo: mean_amazon = amazon['grade'].mean()
 Debo pasar antes la variable a número : [texto del enlace](https://)

In [ ]:

##mean_amazon = amazon['number_of_reviews'].mean()  #no se puede hacer la media con variables tipo texto
 #tipo de variablesprin
print(amazon.iloc[:,1:14].head(1).dtypes)

product_name                                   object
manufacturer                                   object
price                                          object
number_available_in_stock                      object
number_of_reviews                              object
number_of_answered_questions                   object
average_review_rating                          object
amazon_category_and_sub_category               object
description                                    object
product_information                            object
product_description                            object
items_customers_buy_after_viewing_this_item    object
customer_questions_and_answers                 object
dtype: object

In [ ]:
amazon.shape  #contar el numero de columnas

(10004, 895)

In [ ]:
amazon.isnull().sum() #contar los valores 0

uniq_id                          2
product_name                     2
manufacturer                     9
price                         1437
number_available_in_stock     2502
                             ...
Unnamed: 890                 10002
Unnamed: 891                 10002
Unnamed: 892                 10002
Unnamed: 893                 10003
Unnamed: 894                 10003
Length: 895, dtype: int64

In [ ]:
perc = 70.0 # descartamos las columnas con mas del 70% sin valores
min_count =  int(((100 - perc)/100) * amazon.shape[1] + 1)
mod_amazon = amazon.dropna(axis = 1, thresh = min_count)

In [ ]:
mod_amazon.columns

Index(['uniq_id', 'product_name', 'manufacturer', 'price',
       'number_available_in_stock', 'number_of_reviews',
       'number_of_answered_questions', 'average_review_rating',
       'amazon_category_and_sub_category', 'description',
       'product_information', 'product_description',
       'items_customers_buy_after_viewing_this_item',
       'customer_questions_and_answers'],
      dtype='object')

In [ ]:
mod_amazon.dtypes

uniq_id                                        object
product_name                                   object
manufacturer                                   object
price                                          object
number_available_in_stock                      object
number_of_reviews                              object
number_of_answered_questions                   object
average_review_rating                          object
amazon_category_and_sub_category               object
description                                    object
product_information                            object
product_description                            object
items_customers_buy_after_viewing_this_item    object
customer_questions_and_answers                 object
dtype: object

In [ ]:
mod_amazon.describe() ## Nos da un descripcion de los datos

,uniq_id,product_name,manufacturer,price,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers
count,10002,10002,9995,8567,7502,9984.0,9237.0,9984,9312,9351,9943,9350,6936,915
unique,10001,9965,2652,2626,90,290.0,30.0,20,256,8514,9939,8513,6749,910
top,},Polyhedral Dice,LEGO,£9.99,2 new,1.0,1.0,5.0 out of 5 stars,Die-Cast & Toy Vehicles > Toy Vehicles & Acces...,"Welcome to k2, we offer combined items postage...","{""""text"""":""""Fire Tablets""""","Welcome to k2, we offer combined items postage...",http://www.amazon.co.uk/Scalextric | http://ww...,Is it 12 days or 24? // 24
freq,2,3,171,189,1337,3143.0,5796.0,5140,880,113,2,113,38,2

In [ ]:
mod_amazon[["uniq_id", "manufacturer", "price", "number_available_in_stock", "number_of_reviews", "number_of_answered_questions"]] #filtramos que información queremos y que informacion no queremos

,uniq_id,manufacturer,price,number_available_in_stock,number_of_reviews,number_of_answered_questions
0,eac7efa5dbd3d667f26eb3d3ab504464,Hornby,£3.42,5 new,15.0,1.0
1,b17540ef7e86e461d37f3ae58b7b72ac,FunkyBuys,£16.99,NaN,2.0,1.0
2,348f344247b0c1a935b1223072ef9d8a,ccf,£9.99,2 new,17.0,2.0
3,e12b92dbb8eaee78b22965d2a9bbbd9f,Hornby,£39.99,NaN,1.0,2.0
4,e33a9adeed5f36840ccc227db4682a36,Hornby,£32.19,NaN,3.0,2.0
...,...,...,...,...,...,...
9999,44d6967f083825a5de36ad4865a65bcd,Mattel,£22.95,5 new,3,3.0
10000,08f0747b6fc6687215ffb994c3a6fb32,Star Wars,£39.99,NaN,1,3.0
10001,bf6cc073f8f24e6e338190fa16f6ee9d,Olde Scotland Yard Ltd.,£43.99,3 new,1,3.0
10002,cd783d0b8b44e631b9788b203eaaefae,DC Comics,£49.81,3 new,1,3.0
10003,94d18e86e504bee1e392df7e5738b18a,Bandai,£21.20,31 new,11,3.0

In [ ]:
mod_amazon[mod_amazon["uniq_id"] == ("}")] #localizamos datos con errores

,uniq_id,product_name,manufacturer,price,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers
2003,},"{""""text"""":""""Digital & Prime Music""""","panelKey"""":""""Mp3Panel""""}","{""""subtext"""":""""A great selection of apps and g...","text"""":""""Appstore for Android""""","subtextKey"""":""""android-tagline""""","panelKey"""":""""AndroidPanel""""}","{""""text"""":""""Amazon Cloud Drive""""","panelKey"""":""""CloudDrivePanel""""}","panelKey"""":""""KindleReaderPanel""""}","{""""text"""":""""Fire Tablets""""","panelKey"""":""""KindleFireTabletPanel""""}","{""""text"""":""""Fire TV""""","panelKey"""":""""FireTvPanel""""}"
2005,},"{""""text"""":""""Digital & Prime Music""""","panelKey"""":""""Mp3Panel""""}","{""""subtext"""":""""A great selection of apps and g...","text"""":""""Appstore for Android""""","subtextKey"""":""""android-tagline""""","panelKey"""":""""AndroidPanel""""}","{""""text"""":""""Amazon Cloud Drive""""","panelKey"""":""""CloudDrivePanel""""}","panelKey"""":""""KindleReaderPanel""""}","{""""text"""":""""Fire Tablets""""","panelKey"""":""""KindleFireTabletPanel""""}","{""""text"""":""""Fire TV""""","panelKey"""":""""FireTvPanel""""}"

In [ ]:
mod_amazon.drop([2003, 2005], inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
mod_amazon[mod_amazon['number_available_in_stock'].str.contains("used", na = False)].head() ##buscamos los casos de artículos usados

,uniq_id,product_name,manufacturer,price,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers
17,e9ef14a0253f074343b5441540d8471f,Chuggington Interactive Wash and Fuel Set with...,Chuggington,NaN,1 used,2.0,1.0,4.0 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Product Description The Chuggington Interactiv...,Technical Details Item Weight998 g Product Dim...,Product Description The Chuggington Interactiv...,http://www.amazon.co.uk/Chuggington | http://w...,NaN
161,a8d29a2c05bb402335f29f433eb20beb,Hornby R322 OO Scale Class 8F 2-8-0 Steam Loco...,Hornby,NaN,1 used,1.0,2.0,5.0 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,An OO scale model of Stanier's heavy freight s...,Technical Details Manufacturer recommended age...,An OO scale model of Stanier's heavy freight s...,NaN,NaN
198,a293883056a366321acbf8ae75a366a1,Tomy Thomas Track Master Bulgy Train,Tomy,NaN,1 used,2.0,1.0,5.0 out of 5 stars,Characters & Brands > Thomas & Friends > Train...,Manufacturer's Description Motorised die-cast ...,Technical Details Item Weight100 g Product Dim...,Manufacturer's Description Motorised die-cast ...,http://www.amazon.co.uk/Thomas-Friends-Trackma...,NaN
225,476f0014502c44484bd1d5eaeeefd161,MBNF Join In and Play My Blue Nose Friend Bink...,MBNF,NaN,1 used,42.0,1.0,4.8 out of 5 stars,NaN,Product Description Binky is the shy panda who...,Technical Details Item Weight422 g Product Dim...,Product Description Binky is the shy panda who...,http://www.amazon.co.uk/Join-Play-Friend-Peanu...,NaN
232,14ce3f28a67e76f3c0293c27f9f49328,"9"" I Love You Heart Me to You Bear",Me To You,NaN,1 used,1.0,1.0,5.0 out of 5 stars,NaN,"Me to You Bears, also known as the Tatty Teddy...",Technical Details Item Weight272 g Product Dim...,"Me to You Bears, also known as the Tatty Teddy...",NaN,NaN

In [ ]:
item = ["new", "used"] #separamos usados y nuevos y nas
mod_amazon["item_type"] = mod_amazon['number_available_in_stock'].str.extract(f'({"|".join(item)})') ##?¿estudiar la función  extract?
mod_amazon.head(2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,uniq_id,product_name,manufacturer,price,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,item_type
0,eac7efa5dbd3d667f26eb3d3ab504464,Hornby 2014 Catalogue,Hornby,£3.42,5 new,15.0,1.0,4.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Product Description Hornby 2014 Catalogue Box ...,Technical Details Item Weight640 g Product Dim...,Product Description Hornby 2014 Catalogue Box ...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Does this catalogue detail all the previous Ho...,new
1,b17540ef7e86e461d37f3ae58b7b72ac,FunkyBuys® Large Christmas Holiday Express Fes...,FunkyBuys,£16.99,NaN,2.0,1.0,4.5 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Size Name:Large FunkyBuys® Large Christmas Hol...,Technical Details Manufacturer recommended age...,Size Name:Large FunkyBuys® Large Christmas Hol...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,can you turn off sounds // hi no you cant turn...,NaN

In [ ]:
mod_amazon["item_type"].unique()

array(['new', nan, 'used'], dtype=object)

In [ ]:
mod_amazon["price_new"] = mod_amazon["price"].str.split(" ", expand = True).get(0).str.split("£", expand = True).get(1)  #remover el signo libra
mod_amazon.head() #£3.42
mod_amazon[mod_amazon.price_new.str.contains(',', na=False)] #comprobar si el valor está en el rango de miles
mod_amazon["price_new"] = mod_amazon["price_new"].str.replace(",", "") #eliminar la coma
mod_amazon.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,uniq_id,product_name,manufacturer,price,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,item_type,price_new
0,eac7efa5dbd3d667f26eb3d3ab504464,Hornby 2014 Catalogue,Hornby,£3.42,5 new,15.0,1.0,4.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Product Description Hornby 2014 Catalogue Box ...,Technical Details Item Weight640 g Product Dim...,Product Description Hornby 2014 Catalogue Box ...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Does this catalogue detail all the previous Ho...,new,3.42
1,b17540ef7e86e461d37f3ae58b7b72ac,FunkyBuys® Large Christmas Holiday Express Fes...,FunkyBuys,£16.99,NaN,2.0,1.0,4.5 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Size Name:Large FunkyBuys® Large Christmas Hol...,Technical Details Manufacturer recommended age...,Size Name:Large FunkyBuys® Large Christmas Hol...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,can you turn off sounds // hi no you cant turn...,NaN,16.99
2,348f344247b0c1a935b1223072ef9d8a,CLASSIC TOY TRAIN SET TRACK CARRIAGES LIGHT EN...,ccf,£9.99,2 new,17.0,2.0,3.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,Technical Details Manufacturer recommended age...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,http://www.amazon.co.uk/Train-With-Tracks-Batt...,What is the gauge of the track // Hi Paul.Trut...,new,9.99
3,e12b92dbb8eaee78b22965d2a9bbbd9f,HORNBY Coach R4410A BR Hawksworth Corridor 3rd,Hornby,£39.99,NaN,1.0,2.0,5.0 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,Technical Details Item Weight259 g Product Dim...,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,NaN,NaN,NaN,39.99
4,e33a9adeed5f36840ccc227db4682a36,Hornby 00 Gauge 0-4-0 Gildenlow Salt Co. Steam...,Hornby,£32.19,NaN,3.0,2.0,4.7 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,Product Description Hornby RailRoad 0-4-0 Gild...,Technical Details Item Weight159 g Product Dim...,Product Description Hornby RailRoad 0-4-0 Gild...,http://www.amazon.co.uk/Hornby-R2672-RailRoad-...,NaN,NaN,32.19

In [ ]:
mod_amazon["number_available_in_stock"] = mod_amazon["number_available_in_stock"].str.extract("(\d+)").astype(np.float) 
# extract the digits and change the type to float
mod_amazon.dtypes

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

uniq_id                                         object
product_name                                    object
manufacturer                                    object
price                                           object
number_available_in_stock                      float64
number_of_reviews                               object
number_of_answered_questions                    object
average_review_rating                           object
amazon_category_and_sub_category                object
description                                     object
product_information                             object
product_description                             object
items_customers_buy_after_viewing_this_item     object
customer_questions_and_answers                  object
item_type                                       object
price_new                                       object
dtype: object

In [ ]:
mod_amazon["number_of_reviews"] = mod_amazon["number_of_reviews"].str.extract("(\d+)").astype(np.float) #extraemos los numeros y los cambiamos de objeto a float

In [ ]:
mod_amazon.dtypes

uniq_id                                         object
product_name                                    object
manufacturer                                    object
price                                           object
number_available_in_stock                      float64
number_of_reviews                              float64
number_of_answered_questions                    object
average_review_rating                           object
amazon_category_and_sub_category                object
description                                     object
product_information                             object
product_description                             object
items_customers_buy_after_viewing_this_item     object
customer_questions_and_answers                  object
item_type                                       object
price_new                                       object
dtype: object

In [ ]:
numpy.sum()